[package]
name = "imgdown"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
reqwest = "0.11"
regex = "1.0"
url = "2.0"
anyhow = "1.0"
walkdir = "2.3"